test env added

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -57,12 +57,27 @@ jobs:
             # Pull latest image
             docker pull $IMAGE_URI
 
-            # Restart app
+            # ---------test-env--------
             docker stop bookstore-app || true
             docker rm bookstore-app || true
-            docker run -d --name bookstore-app -p 8000:8000 --restart always $IMAGE_URI
+            docker run -d --name bookstore-app -p 8001:8000 --restart always $IMAGE_URI
 
-            echo "App deployed"
+            echo "waiting for test app..."
+            test 5
+            
+            if curl http://localhost:8001; then
+              echo "Test Passed"
+            else
+              echo "test failed"
+              docker logs bookstore-test
+              exit 1
+            fi
+
+            #----------prod-env---------
+            docker stop bookstore-app-prod || true
+            docker rm bookstore-app-prod || true
+            docker run -d -p 8000:8000 --name bookstore-app-prod $IMAGE_URL
+            echo "production-deployed"
 
             # ---------------- MONITORING ----------------
             mkdir -p ~/monitoring
